### ISSUE TITLE
What license is correct?

### ISSUE THREAD

**Issue by lwinkyawmyat** [Rabbit-Converter/Rabbit-Node#3]
[Rabbit-Node](https://github.com/Rabbit-Converter/Rabbit-Node/) library is a awesome library. But, there is two license found in the project that WTFPL and MIT.
May I know what license is correct?

[MIT](https://github.com/Rabbit-Converter/Rabbit-Node/blob/master/LICENSE) or WTFPL.

**Comment by Arkar-Aung** [comment]
Good question. The base library [Rabbit](https://github.com/Rabbit-Converter/Rabbit) itself is under WTFPL license. But each ported library to specific language is under MIT. Only Ko @saturngod can answer this question.

**Comment by saturngod** [comment]
Rabbit Source is WTFPL and maintain by me. Other ported library like node, PHP , Java are maintain by other contributor. It's under MIT license.

Rabbit orignal source is only included .js , .php or .java file. There is no package system. For making packages was done by contributors like @Arkar-Aung
